#!/usr/bin/env bash
# ##########################################################################
#
#              //===//   //=====   //===//   //       //   //===//
#             //    //  //        //    //  //       //   //    //
#            //===//   //=====   //===//   //       //   //===<<
#           //   \\         //  //        //       //   //    //
#          //     \\  =====//  //        //=====  //   //===//   Version III
#
#             ###################################################
#           ======  D E M O N S T R A T I O N   S Y S T E M  ======
#             ###################################################
#
# ############# An Efficient RSerPool Prototype Implementation #############
#
# Copyright (C) 2002-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

# Bash options:
set -e


if [ $# -lt 4 ] ; then
   echo >&2 "Usage: $0 output_file width height input_directory"
   exit 1
fi
OUTPUT="$1"
WIDTH="$2"
HEIGHT="$3"
DIRECTORY="$4"

GM="gm"
SCRIPTPATH=`dirname "$0"`   # NOTE: Current directory may be a build directory!

# ------ Proportions --------------------------------------------------------
logoWidth=0.25        # of Width
logoIndent=0.025      # of Height
websiteWidth=0.925    # of Width
websiteIndent=0.050   # of Height

logoWidthValue=`LC_NUMERIC=C awk "BEGIN { print int(${WIDTH}*${logoWidth}) }"`
logoIndentValue=`LC_NUMERIC=C awk "BEGIN { print int(${HEIGHT}*${logoIndent}) }"`
websiteWidthValue=`LC_NUMERIC=C awk "BEGIN { print int(${WIDTH}*${websiteWidth}) }"`
websiteIndentValue=`LC_NUMERIC=C awk "BEGIN { print int(${HEIGHT}*${websiteIndent}) }"`


tempDirectory=`mktemp -d rserpooldemo-overlay-${WIDTH}x${HEIGHT}.XXXXXXXXXXXXXXXX`

${GM} convert $DIRECTORY/Logo-RSPLIB.png -trim \
   -resize ${logoWidthValue}x \
   +compress ${tempDirectory}/logo.tiff
${GM} convert $DIRECTORY/Website.png -trim \
   -resize ${websiteWidthValue}x \
   +compress ${tempDirectory}/website.tiff

${GM} composite -size ${WIDTH}x${HEIGHT} \
   -gravity NorthEast ${tempDirectory}/logo.tiff -geometry +${logoIndentValue}+${logoIndentValue} \
   xc:none +compress ${tempDirectory}/layer-logo.tiff
${GM} composite -size ${WIDTH}x${HEIGHT} \
   -gravity South -geometry +0+${websiteIndentValue} ${tempDirectory}/website.tiff \
   xc:none +compress ${tempDirectory}/layer-website.tiff

${GM} composite ${tempDirectory}/layer-logo.tiff ${tempDirectory}/layer-website.tiff "$OUTPUT"

rm -rf ${tempDirectory}
