#!/bin/bash -e
# ##########################################################################
#
#              //===//   //=====   //===//   //       //   //===//
#             //    //  //        //    //  //       //   //    //
#            //===//   //=====   //===//   //       //   //===<<
#           //   \\         //  //        //       //   //    //
#          //     \\  =====//  //        //=====  //   //===//   Version III
#
#             ###################################################
#           ======  D E M O N S T R A T I O N   S Y S T E M  ======
#             ###################################################
#
# ############# An Efficient RSerPool Prototype Implementation #############
#
# Copyright (C) 2002-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#


if [ $# -lt 4 ] ; then
   echo >&2 "Usage: $0 output_file width height input_directory"
   exit 1
fi
OUTPUT="$1"
WIDTH="$2"
HEIGHT="$3"
DIRECTORY="$4"

GM="/usr/bin/gm"

# ------ Proportions --------------------------------------------------------
logoWidth=0.25        # of Width
logoIndent=0.025      # of Height
websiteWidth=0.925    # of Width
websiteIndent=0.050   # of Height


# ------ Create logo --------------------------------------------------------
logoWidthValue=`awk "BEGIN { print ${WIDTH}*${logoWidth} }"`
logoIndentValue=`awk "BEGIN { print ${HEIGHT}*${logoIndent} }"`
websiteWidthValue=`awk "BEGIN { print ${WIDTH}*${websiteWidth} }"`
websiteIndentValue=`awk "BEGIN { print ${HEIGHT}*${websiteIndent} }"`

# convert -size ${WIDTH}x${HEIGHT} xc:none \
#    \( $DIRECTORY/Logo-RSPLIB.png -trim +repage -resize ${logoWidthValue}x \) -gravity northeast -geometry +${logoIndentValue}+${logoIndentValue} -composite \
#    \( -background none \
#       \( $DIRECTORY/Website.png     -trim +repage -resize ${websiteWidthValue}x \) -gravity center -append \) \
#          -gravity south -geometry +0+${websiteIndentValue} -composite \
# "$OUTPUT"

tempDirectory=`mktemp -d`

${GM} convert $DIRECTORY/Logo-RSPLIB.png -trim \
   -resize ${logoWidthValue}x \
   ${tempDirectory}/logo.miff
${GM} convert $DIRECTORY/Website.png -trim \
   -resize ${websiteWidthValue}x \
   ${tempDirectory}/website.miff

${GM} composite -size ${WIDTH}x${HEIGHT} \
   -gravity NorthEast ${tempDirectory}/logo.miff -geometry +${logoIndentValue}+${logoIndentValue} \
   xc:none ${tempDirectory}/layer-logo.miff
${GM} composite -size ${WIDTH}x${HEIGHT} \
   -gravity South -geometry +0+${websiteIndentValue} ${tempDirectory}/website.miff \
   xc:none ${tempDirectory}/layer-website.miff

${GM} composite ${tempDirectory}/layer-logo.miff ${tempDirectory}/layer-website.miff "$OUTPUT"

rm -rf ${tempDirectory}
