#!/bin/bash
#
# Thomas Dreibholz's LaTeX Toolchain
# Copyright (C) 2007 by Thomas Dreibholz, dreibh@exp-math.uni-essen.de
#
# $Id: dia2pdf 194 2007-09-04 08:10:00Z dreibh $
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# Contact: dreibh@iem.uni-due.de
#

if [ $# != 2 ] ; then
   echo "Usage: dia2pdf [Source File] [Destination File]"
   exit 1
fi


echo "Converting $1 to $2 ..."
dia -n -t eps-pango -e $2.eps $1
eps2eps $2.eps $2.eps.eps
epstopdf $2.eps.eps --outfile=$2
rm -f $2.eps $2.eps.eps
