#!/usr/bin/env bash
#
# Caption Script
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY# without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -e


# Example:
# Make-Caption Caption.png "Caption Text" 1024 42 "Noto Sans Bold" 60
# Make-Caption Caption.png "Caption Text" 1024 42 "Noto Sans Bold" 60 "#02266b" "#ffd700" 26


# ====== Handle arguments ===================================================
if [ $# -lt 6 ] ; then
   echo >&2 "Usage: $0 output_filename caption_text caption_width caption_height font font_size_percent [foreground [background [transparency]]]"
   exit 1
fi
VERBOSE=1
OUTPUT_FILENAME="$1"
CAPTION_TEXT="$2"
CAPTION_WIDTH=$3
CAPTION_HEIGHT=$4
FONT_NAME="$5"
FONT_SIZE=$6

COLOR_FOREGROUND="#02266b"   # Dark Blue
COLOR_BACKGROUND="#ffd700"   # Gold
TRANSPARENCY=25              # %
if [ $# -gt 6 ] ; then
   COLOR_FOREGROUND="$7"
   if [ $# -gt 7 ] ; then
      COLOR_BACKGROUND="$8"
      if [ $# -gt 8 ] ; then
         TRANSPARENCY="$9"
      fi
   fi
fi


# ====== Call GIMP ==========================================================
rm -f "${OUTPUT_FILENAME}"
( cat <<EOF
(let*
   ((outputFileName   "${OUTPUT_FILENAME}")
    (captionText      "${CAPTION_TEXT}")
    (captionWidth     ${CAPTION_WIDTH})
    (captionHeight    ${CAPTION_HEIGHT})
    (captionFont      "${FONT_NAME}")
    (captionFontSize  (/ (* ${FONT_SIZE} captionHeight) 100))
    (captionOpacity   (- 100 ${TRANSPARENCY}))
    (captionFGColor   "${COLOR_FOREGROUND}")
    (captionBGColor   "${COLOR_BACKGROUND}")
    (theText)
    (drawable)
    (image (car (gimp-image-new captionWidth captionHeight RGB)))
    (layer1 (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 1" captionOpacity NORMAL-MODE)))
    (layer2 (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 2" 100 NORMAL-MODE)))
   )
   ; ------------------------------------------------------------------------
   (gimp-image-add-layer image layer1 0)
   (gimp-image-add-layer image layer2 0)
   (gimp-context-set-background captionBGColor)
   (gimp-context-set-foreground captionFGColor)
   (gimp-drawable-fill layer1 BACKGROUND-FILL)

   (set! theText (car (gimp-text-fontname image layer2 0 0 captionText 0 TRUE captionFontSize PIXELS captionFont) ) )
   (gimp-layer-set-offsets
      theText
      (/ (- captionWidth  (car (gimp-drawable-width  theText))) 2)
      (/ (- captionHeight (car (gimp-drawable-height theText))) 2))

   (gimp-image-merge-visible-layers image CLIP-TO-IMAGE)
   ; (gimp-display-new image)
   ; ------------------------------------------------------------------------
   (set! drawable (car (gimp-image-get-active-layer image)))
   (file-png-save2 RUN-NONINTERACTIVE image drawable outputFileName outputFileName TRUE 9 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
)
(gimp-quit TRUE)
EOF
) | env LANG=C HOME=/tmp gimp --quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch - 2>&1 | \
(
   if [ ${VERBOSE} -ne 0 ] ; then
      cat
   else
      grep -vE "^ts>|(#t)|^Copyright|^Welcome|^using gegl copy|scriptfu-WARNING|LibGimp-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
   fi
)


# ====== Check result =======================================================
if [ ! -e "${OUTPUT_FILENAME}" ] ; then
   echo >&2 "ERROR: ${OUTPUT_FILENAME} has not been produced. Something went wrong!"
   exit 1
fi
