#!/usr/bin/env bash
#
# Thomas Dreibholz's LaTeX Toolchain
# Copyright (C) 2007-2022 by Thomas Dreibholz, dreibh@iem.uni-due.de
#
# $Id: dia2pdf 3353 2011-11-04 16:15:36Z dreibh $
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNES6S FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# Contact: dreibh@iem.uni-due.de
#

if [ $# != 2 ] ; then
   echo "Usage: pdf2png [Source File] [Destination File]"
   exit 1
fi


# echo "Converting $1 to $2 from Dia to PDF ..."

gs \
 -q \
 -dNOPAUSE \
 -dBATCH \
 -sDEVICE=pngalpha \
 -r600 \
 -dDownScaleFactor=2 \
 -dUseCropBox \
 -sOutputFile="$2" \
 "$1"
