#!/usr/bin/env bash
# * ##########################################################################
# *
# *              //===//   //=====   //===//   //       //   //===//
# *             //    //  //        //    //  //       //   //    //
# *            //===//   //=====   //===//   //       //   //===<<
# *           //   \\         //  //        //       //   //    //
# *          //     \\  =====//  //        //=====  //   //===//   Version III
# *
# *             ###################################################
# *           ======  D E M O N S T R A T I O N   S Y S T E M  ======
# *             ###################################################
# *
# * ############# An Efficient RSerPool Prototype Implementation #############
# *
# * Copyright (C) 2002-2023 by Thomas Dreibholz
# *
# * This program is free software: you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation, either version 3 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program.  If not, see <http://www.gnu.org/licenses/>.
# *
# * Contact: dreibh.iem.uni-due.de

if [ $# -lt 1 ] ; then
   echo >&2 "Usage: PlanetLabScenario-Demo1 [start|restart|stop|stopall] {Options}"
   exit 1
fi

MODE=$1
shift

if [ "x$MODE" = "xstop" -o "x$MODE" = "xstopall" ] ; then
   ./RemoteComponentControl ./PlanetLab-User.config "\$CC_HOST_STUTTGART" ./PlanetLabScenario.config PE-STATIC 5 stop $@ &
   ./RemoteComponentControl ./PlanetLab-User.config "\$CC_HOST_JERUSALEM" ./PlanetLabScenario.config PE-STATIC 3 stop $@ &
   ./RemoteComponentControl ./PlanetLab-User.config "\$CC_HOST_SANDIEGO"  ./PlanetLabScenario.config PE-STATIC 6 stop $@ &
   wait
   if [ "x$MODE" = "xstopall" ] ; then
      ./PlanetLabScenario-StopAll stop
   fi
else
   ./PlanetLabScenario-StartAll 0 0 0 $@ &
   ./RemoteComponentControl ./PlanetLab-User.config "\$CC_HOST_STUTTGART" ./PlanetLabScenario.config PE-STATIC 5 $MODE -identifier=0x104 $@ &
   ./RemoteComponentControl ./PlanetLab-User.config "\$CC_HOST_JERUSALEM" ./PlanetLabScenario.config PE-STATIC 3 $MODE -identifier=0x102 $@ &
   ./RemoteComponentControl ./PlanetLab-User.config "\$CC_HOST_SANDIEGO"  ./PlanetLabScenario.config PE-STATIC 6 $MODE -identifier=0x105 $@ &
   wait
fi
